---
- name: "docker-app {{ dockerapp_name }} envfile creation"
  template:
    src: "{{ dockerapp_envfile_local_path }}"
    dest: "{{ dockerapp_config_path }}/{{ dockerapp_envfile_name }}"
    owner: root
    group: root
    mode: 0600
  when: dockerapp_envfile_local_path is defined

- name: "docker-app {{ dockerapp_name }} compose file templating"
  template:
    src: "{{ dockerapp_compose_template_path }}"
    dest: "{{ dockerapp_config_path }}/{{ dockerapp_compose_file_name }}"
    owner: root
    group: root
    mode: 0600

- name: "docker-app {{ dockerapp_name }} compose run"
  community.docker.docker_compose_v2:
    project_src: "{{ dockerapp_config_path }}"
    files: [ "{{ dockerapp_compose_file_name }}" ]
    recreate: "{{ dockerapp_recreate }}"